### ISSUE TITLE
Create popup HTML&CSS

### ISSUE THREAD

**Issue by stanislavBenet** [stanislavBenet/homepage#14]
Create popup mechanism with CSS%HTML

**Comment by jamiuabdulkareem** [comment]
can i pull CSS code for the popup without using JavaScript

**Comment by stanislavBenet** [comment]
sure

вс, 18 июн. 2023 г. в 19:28, Jamiu Abidemi Abdulkareem <
***@***.***>:

**Comment by stanislavBenet** [comment]
Done
